services:
  - type: web
    name: sexx-guardian
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python sexx_render_guardian.py
    runtime: python
    pythonVersion: 3.10
