services:
  - type: web
    name: sexx-guardian
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn sexx_render_guardian:app --bind 0.0.0.0:10000
    autoDeploy: true
